### ISSUE TITLE
Publish visualization as github project pages

### ISSUE THREAD

**Issue by jpasini** [jpasini/run169#14]
Already started, but must be sure to publish the final version. The "dist/bundle.js" file is only present in the gh-pages branch, and commits there should be only sporadic, to prevent repo bloat.

- [x] Add project website to repo description.
- [x] Update README with deployment instructions

**Comment by dbeach24** [comment]
I like that you've explicitly listed publishing the visualization as a project page as a task.  One of the things I've been thinking about is how I'm going to build a portfolio of my work, and project pages look like a good way to go.  I'm going to add this to my task list.
