### ISSUE TITLE
Add a widget to select a member

### ISSUE THREAD

**Issue by jpasini** [jpasini/run169#7]
This may be tricky, as there are over 1,000 members. The end result should not require excessive scrolling to find a person. Perhaps bootstrap has a good solution that also accepts keyboard shortcuts or matching based on partial typing.

**Comment by curran** [comment]
You may want to have a look at https://semantic-ui.com/

They have a really nice search box feature that should be relatively straightforward to get working

https://semantic-ui.com/modules/search.html
